import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/style/globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/footer-section";
import VideoPlayer from "@/components/shared/video-player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <VideoPlayer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
